# Generated by Django 4.0 on 2023-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='contObj',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='contSubj',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
