# Generated by Django 4.0 on 2023-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0002_sentiment_contobj_sentiment_contsubj'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='sent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='subreddit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
