# Generated by Django 4.0 on 2023-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0004_alter_sentiment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.CharField(max_length=200),
        ),
    ]
