# Generated by Django 4.0 on 2023-06-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0007_remove_sentiment_subreddit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='sent',
        ),
    ]
