# Generated by Django 4.0 on 2023-06-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0008_remove_subreddit_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='sent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
