# Generated by Django 4.0 on 2023-06-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0009_subreddit_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subreddit.subreddit'),
        ),
    ]
