# Generated by Django 4.0 on 2023-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0010_sentiment_subreddit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='contObj',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='contSubj',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='sent',
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='subreddit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
