# Generated by Django 4.0 on 2023-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0011_remove_sentiment_contobj_remove_sentiment_contsubj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='sent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
